### ISSUE TITLE
Drawing a polygon in multi-map environment doesn't work.

### ISSUE THREAD

**Issue by Ish-rivera** [missioncommand/emp3-android#1]
Drawing a polygon in multi-map environment doesn't work.

Issue has been reported to NASA, awaiting fix.

Same issue exists for Circle, Ellipse and Rectangle.
In Capability Tester, Launch two map instances.
Start "Basic Test" and run for any shape and you will notice that shapes are not shown as expected.

**Comment by empbarney** [comment]
This is no longer an issue. Verified with Capability Tester.
