### ISSUE TITLE
KML Export of SP MilStd hot spot

### ISSUE THREAD

**Issue by Ish-rivera** [missioncommand/emp3-android#101]
When exporting to KML, the hot spot of the single point milstd feature is not matching when plotted in google earth.

**Comment by Ish-rivera** [comment]
To test use branch #101-KML-Export-of-SP-MilStd-hot-spot.

1) With test Basic use the zoom button at the top left and zoom in to less than 10,000 m altitude.
2) Draw A milstd single point feature a the center of the viewing area. Give the icon a name.
3) Make sure the icon is Un Selected.
4) Using the menu select a KML export of the map and transfer the mapexport.kml to your laptop.
5) Import the mapexport.kml into google earth.
6) Via the google earth menu, add a placemark at the same location as the milstd icon.
7) The 2 icons should have there hot spot at the same location.
8) If the MilStd icon is NOT a headquarter the hot spot should be at the center of symbol portion of the icon. HQ icons have their hot spot at the bottom of the flag pole.

**Comment by mubinakhan** [comment]
[overlayexport.kml[1].txt](https://github.com/missioncommand/emp3-android/files/883120/overlayexport.kml.1.txt)

**Comment by mubinakhan** [comment]
[overlayexport (1).zip](https://github.com/missioncommand/emp3-android/files/883462/overlayexport.1.zip)

**Comment by mubinakhan** [comment]
![ge](https://cloud.githubusercontent.com/assets/25485443/24555321/b3a101c0-15fe-11e7-969c-0e3aa309f173.jpg)

**Comment by Ish-rivera** [comment]
![flagandhotspot](https://cloud.githubusercontent.com/assets/7874003/24555674/03f00aee-1600-11e7-9d9c-06de79663deb.png)

**Comment by mubinakhan** [comment]
![ge](https://cloud.githubusercontent.com/assets/25485443/24555972/edacd158-1600-11e7-8f9b-f1f3fa108462.jpg)

**Comment by mubinakhan** [comment]
![ge1](https://cloud.githubusercontent.com/assets/25485443/24556214/a610d302-1601-11e7-8f73-1e241e5fbe46.jpg)
