### ISSUE TITLE
Need unique object for identifying self-events in 'add' methods

### ISSUE THREAD

**Issue by rsupnekar** [missioncommand/emp3-android#108]
Currently, addFeature and addCamera and other add methods generate events, but there is no way for the users to tell if it is their own event or someone else's.

**Comment by rsupnekar** [comment]
Currently, addFeature and addCamera and other add methods generate events, but there is no way for the users to tell if it is their own event or someone else's.

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
see #91

**Comment by rsupnekar** [comment]
A new issue will be opened for tests
