### ISSUE TITLE
mgrs grid lines

### ISSUE THREAD

**Issue by mubinakhan** [missioncommand/emp3-android#109]
To Test 
Use test basic.

   * Via the menu / settings / Map Grid. Select MGRS.
   * The MGRS grid should show up on the map.
    *Pan / Zoom the map.
   * The grid should correctly redraw.
    *Alter the camera heading, title and roll
   * The map slows down for few seconds and stops 
   * After waiting few seconds it starts working again.
   * This issue only appear In Nexus tablet.
  * map only slows down after  zoomed out and then zooming in it again.
![screenshot_20170329-142002 1](https://cloud.githubusercontent.com/assets/25485443/24469735/8b618b64-148a-11e7-84f3-52e1ce704f27.png)

Same thing happens when selected UTM  Grid 
  See image attached to see the locality
![screenshot_20170329-141653 1](https://cloud.githubusercontent.com/assets/25485443/24469637/1bea0752-148a-11e7-8d86-0cfaf1e2997d.png)
 and heading of the map

**Comment by Ish-rivera** [comment]
Test revealed that the delay is injected by the world wind lib when rendering rhumb lines. We have submitted the issue to NASA and await a resolution.
