### ISSUE TITLE
Display KML Service Data

### ISSUE THREAD

**Issue by Ish-rivera** [missioncommand/emp3-android#11]
3.4.1.4 Display KML Service Data
Requirement: The Map Engine (Smart Client) shall display data loaded obtained from external KML services.
Rationale: At times, it may be necessary to display geospatial information from other systems. The KML format is XML notation for geographic annotation and visualization.

**Comment by empbarney** [comment]
1. Features created by KMZ are treated as a special layer in Map Instance. They are not added to any overlay within the core.
2. Features created via KMZ are not returned when getAllMapFeatures is executed.
3. No event is generated when KMZ processing is complete or fails.
4. KMZ referring to another KMZ is not supported as our parser skips over network links.
5. Need ti make a decision on mirror-cache and KML service.

**Comment by empbarney** [comment]
Test Instructions:

branch: feature/emp3-android#11-Display-KML-Service-Data

Install Capability Tester.
Launch Map and then start "KML Service" test. (This is a new test).

1. If you have network access from your tablet you can try the URLs under "Network URL"
       - Once you select a URL you will see a popup, enter a name for your service, It should be unique.
2. Push all the files from tests/data/kml-samples and tests/data/geojson-samples to /sdcard/testFiles.
3. Now select "File URL" and pick any URL. 
       - Once you select a URL you will see a popup, enter a name for your service, It should be unique.
4. You can use "Show Services" to see added services.
5. You can remove added services by using "remove Services" button.
6. Under "..." there is a "custom URL" option. You can select network KMZ if your tablet has network access.
