### ISSUE TITLE
Add methods to support operations via geoId?

### ISSUE THREAD

**Issue by ee11cbb19052e40b07aac0ca060c23ee** [missioncommand/emp3-android#112]
When interacting with the API for the purpose of removing features or overlays, for example, a reference to the target object must be supplied to the remove method. Should we accept geoIds as well?

**Comment by Ish-rivera** [comment]
I agree

**Comment by empbarney** [comment]
1. By doing this we are accepting that GEOID is a key (possibly a primary key), should we then go ahead and make it immutable after creating a constructor that takes GEOID as argument. We had this discussion earlier and RII had suggested that as long as such a constructor exists they are ok with this change.
2. Should we then allow other API like "select" or "apply" to with GEOID as arguments?

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
@empbarney What concerns should we be aware of if we accept GEOID as a key?

---

> Should we then allow other API like "select" or "apply" to with GEOID as arguments?

For _select_ methods like the following: `void selectFeatures(IMap map, List<IFeature> features)`, I would think yes. Similar to how `void removeFeatures(List<IFeature> features)` would also now accept a List of GEOIDs.

For _apply_ method, I'm not so sure. Doesn't _apply_ imply the current object? Are there situations where that is not the case?

**Comment by empbarney** [comment]
You are correct, apply method is not relevant.

How about editFeature? setVisibility?

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
I'm not sure. Doing so would add to the API extensively.

**Comment by empbarney** [comment]
Consistency vs API size, it's a trade. We should document why we are not doing it.

**Comment by rsupnekar** [comment]
This feature was primarily for MirrorCache, and will not be in ER3.
