### ISSUE TITLE
Add Decimal Degree Map Grid

### ISSUE THREAD

**Issue by Ish-rivera** [missioncommand/emp3-android#132]

**Comment by Ish-rivera** [comment]
To test use branch 132-Add-Decimal-Degree Map Grid.

1) Start Test-Basic.
2) With the menu select settings / Map Grid / DD
3) Zoom in and out and pan the map.
4) The grid should redraw corectly.

**Comment by mubinakhan** [comment]
![screenshot_20170406-154647 1](https://cloud.githubusercontent.com/assets/25485443/24772733/7ff16cb6-1ae0-11e7-88b0-b7ea560a2193.png)
![screenshot_20170406-154807 1](https://cloud.githubusercontent.com/assets/25485443/24772745/8777eb2c-1ae0-11e7-8f7f-a349e5d19b03.png)

**Comment by mubinakhan** [comment]
* Zooming out and spinning by touching the screen ,the map slows down and after few seconds it becomes unresponsive.Please see the attached image

**Comment by Ish-rivera** [comment]
Pull the latest and retest please.

**Comment by mubinakhan** [comment]
Re-tested.
Reintegrate
