### ISSUE TITLE
test-basic: Draw Polygon: too many dots!

### ISSUE THREAD

**Issue by ee11cbb19052e40b07aac0ca060c23ee** [missioncommand/emp3-android#142]
![image](https://cloud.githubusercontent.com/assets/25460191/24928691/49eba0ce-1ed1-11e7-9aa9-19e123a02aae.gif)

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
Please see animation.

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
Longer video showing the steps to reproduce:

![bandicam 2017-04-12 10-16-55-155](https://cloud.githubusercontent.com/assets/25460191/24962261/721e1f5c-1f69-11e7-8942-2af394c117e7.gif)

**Comment by Ish-rivera** [comment]
To test use branch #142 polygon-too-many-dots.

1) With Test-Basic draw a polygon as shown above and save.
2) Place the polygon into edit mode.
3) Add a CP by dragging the green control point as shown above.
4) Double tap on the blue CP created to delete it.
5) The CP should get deleted and the polygon should revert to its original shape.

**Comment by mubinakhan** [comment]
Reintegrate
