### ISSUE TITLE
test-basic: Draw Polygon: deselected line is thicker than selected line

### ISSUE THREAD

**Issue by ee11cbb19052e40b07aac0ca060c23ee** [missioncommand/emp3-android#143]
This is deceiving in determining if something has been selected or not.

![image](https://cloud.githubusercontent.com/assets/25460191/24918050/f944c9bc-1eac-11e7-9bcf-e6c51ec0f7f0.png)

**Comment by Ish-rivera** [comment]
The style of a selected line or polygon is not necessarily wider.
