### ISSUE TITLE
test-basic: Draw Polygon: New segments are created unexpectedly

### ISSUE THREAD

**Issue by ee11cbb19052e40b07aac0ca060c23ee** [missioncommand/emp3-android#144]
![image](https://cloud.githubusercontent.com/assets/25460191/24918462/8285ba28-1eae-11e7-9e11-a2508a5dfc9e.png)

![image](https://cloud.githubusercontent.com/assets/25460191/24918477/8d28e77a-1eae-11e7-8467-cbe22af829d4.png)

![image](https://cloud.githubusercontent.com/assets/25460191/24918480/90c0ba48-1eae-11e7-9b2b-70f7665d2624.png)

**Comment by Ish-rivera** [comment]
This behavior is by design. New position are added to the end of the position list.

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
Looking at the last picture, two new points were added when clicking in that one location. I think due to being too close to the green circle?

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
![b](https://cloud.githubusercontent.com/assets/25460191/24960347/8ab79b84-1f63-11e7-9b2d-02cf327f2b73.PNG)

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
Video from `bugfix/#144-Draw-Polygon-segments-created-unexpectedly` (98aa5c82e688681f73433f9adc589089888aa651) :

![bandicam 2017-04-13 10-06-31-494](https://cloud.githubusercontent.com/assets/25460191/25008258/3176b3f6-2031-11e7-8166-73a310cddd7c.gif)

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
Following is log from clicking once in the area indicated above:

```
04-19 12:52:20.874 3388-3388/mil.emp3.dev_test_sdk D/PickNavigateController: Picked Polygon
04-19 12:52:20.931 3388-3388/mil.emp3.dev_test_sdk I/PickNavigateController: ACTION_UP evt NOT dragging. Picks 1.
04-19 12:52:21.169 3388-3388/mil.emp3.dev_test_sdk D/MainActivity: Draw Update.
04-19 12:52:21.169 3388-3388/mil.emp3.dev_test_sdk I/MainActivity:    Draw Update COORDINATE_ADDED indexes:{5}
04-19 12:52:21.169 3388-3388/mil.emp3.dev_test_sdk D/StorageObjectWrapper: isOnMap parentRelationship 333a5a31-cedb-4d31-83f4-12c9c8379138
04-19 12:52:21.174 3388-3388/mil.emp3.dev_test_sdk D/MainActivity: Draw Update.
04-19 12:52:21.175 3388-3388/mil.emp3.dev_test_sdk I/MainActivity:    Draw Update COORDINATE_ADDED indexes:{6}
04-19 12:52:21.175 3388-3388/mil.emp3.dev_test_sdk D/StorageObjectWrapper: isOnMap parentRelationship 333a5a31-cedb-4d31-83f4-12c9c8379138
04-19 12:52:21.221 3388-3410/mil.emp3.dev_test_sdk W/EGL_emulation: eglSurfaceAttrib not implemented
04-19 12:52:21.221 3388-3410/mil.emp3.dev_test_sdk W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x9ca53020, error=EGL_SUCCESS
```

**Comment by Ish-rivera** [comment]
To test use branch #144

1) With Test Basic draw a polygon and save it.
2) Place the polygon back into draw mode by long pressing.
3) To add a CP tap on the edge of the polygon.
4) Drag the newly created CP away from its current location.
5) There should only be one newly created CP. (See clip above)

**Comment by mubinakhan** [comment]
Reintegrate
