### ISSUE TITLE
test-basic: Draw Polygon: extra segment sometimes gets created

### ISSUE THREAD

**Issue by ee11cbb19052e40b07aac0ca060c23ee** [missioncommand/emp3-android#145]
It looks like the code is getting confused with how to handle overlapping 'circles'.

![image](https://cloud.githubusercontent.com/assets/25460191/24920197/581ad5ec-1eb4-11e7-9fdc-fc21e0f40c13.png)

![image](https://cloud.githubusercontent.com/assets/25460191/24920203/5b43f5e6-1eb4-11e7-8fa2-d867e218b05c.png)

![image](https://cloud.githubusercontent.com/assets/25460191/24920204/5d284fa6-1eb4-11e7-92ff-6910870beddd.png)

**Comment by mubinakhan** [comment]
Reinetgrate
