### ISSUE TITLE
test-basic: Draw Circle: the circle looks more like an ellipse

### ISSUE THREAD

**Issue by ee11cbb19052e40b07aac0ca060c23ee** [missioncommand/emp3-android#147]
![bandicam 2017-04-11 16-25-41-960](https://cloud.githubusercontent.com/assets/25460191/24929443/eddfbf9c-1ed3-11e7-9c9b-63e5ec89f90c.gif)

![bandicam 2017-04-11 16-29-32-491](https://cloud.githubusercontent.com/assets/25460191/24929530/46184bca-1ed4-11e7-976d-e201dd74a3f5.gif)

**Comment by Ish-rivera** [comment]
![big-circle-2017-04-13-082629](https://cloud.githubusercontent.com/assets/7874003/25004601/2635f578-2023-11e7-8c01-3f59cbd96815.png)
This is a screen shot of a big circle with 4 icons 1 at 45.0 deg from center at the radius distance from the center, the 2nd at 135.0, 3rd at 225.0 and the 4th at 315. As you can see at these sizes circle and ellipses do not render correctly.

**Comment by Ish-rivera** [comment]
This issue has been placed on hold until a renderer fix is available.

**Comment by mdeutch3** [comment]
A fix for this issue was checked into mil-sym-android repository on 4-21-17.

**Comment by mubinakhan** [comment]
Reintegrate
