### ISSUE TITLE
test-basic: Draw Ellipse: control points(?) don't stick to ellipse perimeter

### ISSUE THREAD

**Issue by ee11cbb19052e40b07aac0ca060c23ee** [missioncommand/emp3-android#148]
![bandicam 2017-04-11 16-35-00-358](https://cloud.githubusercontent.com/assets/25460191/24929755/0ec65a94-1ed5-11e7-988b-a1531e2a2137.gif)

**Comment by mubinakhan** [comment]
Reintegrate
