### ISSUE TITLE
test-basic: Draw Rectangle: when control point gets close to center when resizing, the map moves too

### ISSUE THREAD

**Issue by ee11cbb19052e40b07aac0ca060c23ee** [missioncommand/emp3-android#149]
![bandicam 2017-04-11 16-41-14-907](https://cloud.githubusercontent.com/assets/25460191/24929994/ec444548-1ed5-11e7-901e-e1d27f5e7ed7.gif)

![bandicam 2017-04-11 16-45-25-549](https://cloud.githubusercontent.com/assets/25460191/24930134/71f78132-1ed6-11e7-8e8c-bbb10fdddc04.gif)

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
This also affects squares.

**Comment by empbarney** [comment]
Issue #149 and Issue #150 should be tested with branch: feature/emp3-android#149-Rectangle-Resize-Moves-Map
Use the description of the issues to execute test procedures.

**Comment by mubinakhan** [comment]
![screenshot_20170419-103708 1](https://cloud.githubusercontent.com/assets/25485443/25185696/07600aa8-24ec-11e7-8095-117614ab3406.png)

**Comment by mubinakhan** [comment]
Reintegrate
