### ISSUE TITLE
test-basic: Draw Rectangle: control points appear to float above perimeter

### ISSUE THREAD

**Issue by ee11cbb19052e40b07aac0ca060c23ee** [missioncommand/emp3-android#150]
![bandicam 2017-04-11 16-54-35-248](https://cloud.githubusercontent.com/assets/25460191/24930619/12daa7fe-1ed8-11e7-9266-a4a99f0de605.gif)

---

# Instead, I would expect behavior similar to the following:
![bandicam 2017-04-11 16-55-12-021](https://cloud.githubusercontent.com/assets/25460191/24930641/2769af94-1ed8-11e7-85ee-0928170faa74.gif)

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
This also affects squares

**Comment by empbarney** [comment]
This is caused by  the bulkFeatureList implemented in StorageManager. If you set MAX_BULK_FEATURE_APPLY_COUNT = 0 you will notice that behavior will be as you expect.

**Comment by empbarney** [comment]
Issue #149 and Issue #150 should be tested with branch: feature/emp3-android#149-Rectangle-Resize-Moves-Map
Use the description of the issues to execute test procedures.

**Comment by mubinakhan** [comment]
![screenshot_20170419-103708 1](https://cloud.githubusercontent.com/assets/25485443/25185648/e5700d94-24eb-11e7-9980-3102de5ab1cd.png)

**Comment by mubinakhan** [comment]
Reinetgrate

**Comment by mubinakhan** [comment]
Reintegrate
