### ISSUE TITLE
ZoomTo doesn't work on GeoJSON feature

### ISSUE THREAD

**Issue by empbarney** [missioncommand/emp3-android#155]
Maybe getFeatureBoundingBox should be added to this feature.

**Comment by mubinakhan** [comment]
![screenshot_20170413-105634 1](https://cloud.githubusercontent.com/assets/25485443/25010420/16743b6c-2038-11e7-91bf-51e4f36ff077.png)

**Comment by mubinakhan** [comment]
Reintegrate
