### ISSUE TITLE
Feature.apply() can fail silently

### ISSUE THREAD

**Issue by empbarney** [missioncommand/emp3-android#16]
/**
     * Once application has added a feature to an overlay, it can change one or more attributes of the Feature and invoke the apply method to
     * have those changes reflected on the display. This is typically used to change position(s) as battle field objects move around.
     */
    @Override
    public void apply() {
        try {
            storageManager.apply(this, true);
        } catch(EMP_Exception e) {
            e.printStackTrace();
        }
    }

We should flow the exception to application else application presumes that apply was successful. One example is where apply is invoked on a Feature that was never added to the Map.

**Comment by rsupnekar** [comment]
Closed as non-issue.  The CMAPI exceptions are passed to the caller.  The others are handled within EMP.
