### ISSUE TITLE
Test KML parsing and update Capability Tester

### ISSUE THREAD

**Issue by empbarney** [missioncommand/emp3-android#164]
Test KML parsing and update Capability Tester

**Comment by empbarney** [comment]
Test instructions:

build feature/emp3-android-kml-testing and install.

on the device start ApplicationManage from 'settings'
Look for EMp3 Capability tester and select.
Go to the "Permissions' item on the displayed list
Turn on 'storage' permission.

use 'adb shell' command to connect to the device.
create a directory using 'mkdir /sdcard/testFiles'
Push following files to your devices using adb command:

tests/data/kml-samples/kml_samples.xml
tests/data/heojson-samples/cmapi.geojson.xm

Now start Capability tester, launch map, and then start AddRemoveGet test.
Add the overlay, then select KML under add feature.
You will see a popup with name of the file kml_samples.kml select and apply.
You should see place marks in the SF/Cal area.

**Comment by mubinakhan** [comment]
![screenshot_20170414-165345 1](https://cloud.githubusercontent.com/assets/25485443/25055885/7216c43e-2133-11e7-9efa-ee8f0ff7da8d.png)

**Comment by mubinakhan** [comment]
![screenshot_20170414-165543 1](https://cloud.githubusercontent.com/assets/25485443/25055893/7c8bc6b2-2133-11e7-8638-3a5578f9a1b5.png)

**Comment by mubinakhan** [comment]
![screenshot_20170414-165345 1](https://cloud.githubusercontent.com/assets/25485443/25055901/8a9706f4-2133-11e7-81bb-df52a1b9cc1b.png)

**Comment by mubinakhan** [comment]
![screenshot_20170414-170135 1](https://cloud.githubusercontent.com/assets/25485443/25055941/bd0bf5ae-2133-11e7-8489-6f0bdf90cf83.png)

**Comment by mubinakhan** [comment]
Reintegrate
