### ISSUE TITLE
Adding features after orientation change...

### ISSUE THREAD

**Issue by empbarney** [missioncommand/emp3-android#165]
I'm building an Android app using EMP3. I have added features, added a WMS, and have set the camera. When I change the device orientation, I use EMP3LifeCycleManager to save the state of the application which is correctly being restored. However, when I try to add more features to the overlay after the orientation switch, they do not render. I know the overlay exists because features I added before are on the map, and I can retrieve a reference to the overlay via the map's getAllOverlays method as well. No exceptions are being thrown. Any idea what the issue might be? And if not, is there a better way to retain map state after configuration changes?

**Comment by empbarney** [comment]
Updated Capability tester to restore data on orientation change. I am not seeing the issue posted here. I have requested for code.

**Comment by empbarney** [comment]
Test instructions:

1. build branch: feature/emp3-android#163-KML-Graphics-Missing
2. Install Capability Tester and Launch map.
3. Run Add Remove Get Test and add overlay and a Geo Point  feature.
4. Now rotate the device, you should see the map get redrawn, make sure that the point you added is still there by using "Locate"
5. Run Add Remove Get Test and add another Geo Point. You should now have two points on the map. (Note you shouldn't have to add an overlay as it is already there)
Repeat 4 & 5.

**Comment by mubinakhan** [comment]
![screenshot_20170418-125802 1](https://cloud.githubusercontent.com/assets/25485443/25143120/490e4eb6-2437-11e7-8de9-a182233c69c2.png)

**Comment by mubinakhan** [comment]
![screenshot_20170418-125859 1](https://cloud.githubusercontent.com/assets/25485443/25143138/545f3140-2437-11e7-9875-8cc12a6a80f0.png)

**Comment by mubinakhan** [comment]
Reintegrate
