### ISSUE TITLE
Update Polygon Draw and Edit behavior

### ISSUE THREAD

**Issue by Ish-rivera** [missioncommand/emp3-android#167]
Update android polygon draw and edit behavior with the Web draw and edit behavior.

**Comment by Ish-rivera** [comment]
To test use branch #167-update-polygon ....

1) Using Test-Basic, Draw a polygon and test all draw motions.
2) Complete the draw.
3) Double tap on the polygon to place it into edit mode.
4) Tap on the map. No control points should be added.
5) Move the green control point to modify the shape.
6) Double tap on control points to delete the CP.
7) Complete the edit.
8) While the polygon is selected, long tap on the polygon.
9) This should place the feature back into draw mode.
10) Tap on the map.
11) A new control point is created at the double tap location and is added at the end of the polygons position list.

**Comment by mubinakhan** [comment]
What went wrong:
Execution failed for task ':emp3-android-sdk-view:testDebugUnitTest'.
> There were failing tests. See the report at: file:///C:/Users/mubina.khan/Code       2/emp3-android/sdk/sdk-view/build/reports/tests/testDebugUnitTest/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug        option to get more log output.

**Comment by Ish-rivera** [comment]
I fixed it. Try again.

**Comment by mubinakhan** [comment]
![screenshot_20170418-145637 1](https://cloud.githubusercontent.com/assets/25485443/25148726/e0867220-2449-11e7-8813-f3cf636cc8db.png)

**Comment by mubinakhan** [comment]
Reintegrate
