### ISSUE TITLE
Update line draw to place new coordinates at the begining

### ISSUE THREAD

**Issue by Ish-rivera** [missioncommand/emp3-android#171]
Updated all line Draw editing to place new coordinates at the beginning of the position list.

**Comment by Ish-rivera** [comment]
To test use branch #171 update line draw ...

1) With test basic draw a TG / C2GM / Aviation / Line / Air Corridor.
2) As points are added they are added to the beginning of the position list. Save it.
3) Place it into edit mode (Double tap while its selected) and test edit operations. (tapping on the map to add new coordinates is not supported in edit mode). Then save.
4) Place it back into draw mode (long tap while its selected) and test draw operations. Tapping on  the map to add coordinates is supported in draw mode.

Repeat step 1 - 4 with TG / C2GM / Offense / Lines / Axis of Advance / Axis of Advance Aviation.
Repeat steps 1 - 4 with TG / TASKS / Follow and Assume

**Comment by mubinakhan** [comment]
![screenshot_20170419-181452 1](https://cloud.githubusercontent.com/assets/25485443/25204530/dfe9b6d2-252b-11e7-8ee3-a4e440aea498.png)

**Comment by mubinakhan** [comment]
In progress

**Comment by mubinakhan** [comment]
![screenshot_20170420-101955 1](https://cloud.githubusercontent.com/assets/25485443/25235300/c00a5196-25b2-11e7-9b10-735bd460b4f3.png)

**Comment by mubinakhan** [comment]
![screenshot_20170420-102009 1](https://cloud.githubusercontent.com/assets/25485443/25235347/dae32394-25b2-11e7-9d5f-07161b130f88.png)

**Comment by mubinakhan** [comment]
![screenshot_20170420-102439 1](https://cloud.githubusercontent.com/assets/25485443/25235492/424db562-25b3-11e7-8ea0-6087806b0ff4.png)

**Comment by mubinakhan** [comment]
Reintegrate
