### ISSUE TITLE
null checking (various / compiled list)

### ISSUE THREAD

**Issue by ee11cbb19052e40b07aac0ca060c23ee** [missioncommand/emp3-android#172]
Inconsistent internal behavior when StorageManager.getMapMapping returns null:
* if calling the selectFeatures method, it simply returns
* if calling setIconSize method, it throws an exception

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
__[ StorageManager::processVisibilityList ]__
```java
void processVisibilityList(IMap map, IdentifierVisibilityHash idVisibilityList, Object userContext);
```

It is possible to reach this method with a null mapInstance instance.
Should the calling method be responsible for checking if this mapping exists and handle appropriately?

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
__[ MapStatus::canPlot ]__

```java
boolean canPlot(IFeature oFeature);
```

It is possible to reach this method with a null oMapCapabilities object.
This is due to not enforcing a check for the MAP_READY state before allowing MapStatus method invocations.

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
@Ish-rivera @empbarney  FYI

**Comment by rsupnekar** [comment]
In selectFeatures, null is OK because null does not select any features.
In setIconSize an exception is thrown because the operation fails.
