### ISSUE TITLE
Test Polygon Graphic features

### ISSUE THREAD

**Issue by Ish-rivera** [missioncommand/emp3-android#173]
Test drawing editing and renderering of the following MilStd tactical graphics in development.

- [ ] General Area          => TACTICAL GRAPHICS / COMMAND AND CONTROL AND GENERAL MANEUVER / GENERAL AREAS

- [ ] Objective             => TACTICAL GRAPHICS / COMMAND AND CONTROL AND GENERAL MANEUVER / OFFENSE / AREAS / OBJECTIVE

- [ ] Assembly Area         => TACTICAL GRAPHICS / COMMAND AND CONTROL AND GENERAL MANEUVER / GENERAL / AREAS / ASSEMBLY AREA

- [ ] Named area of interest=> TACTICAL GRAPHICS / COMMAND AND CONTROL AND GENERAL MANEUVER / SPECIAL / AREA / NAMED AREA OF INTEREST (NAI)

- [ ] Target area of interest
                        => TACTICAL GRAPHICS / COMMAND AND CONTROL AND GENERAL MANEUVER / SPECIAL / AREA / TARGETED AREA OF INTEREST (TAI)

- [ ] Landing zones         => TACTICAL GRAPHICS / COMMAND AND CONTROL AND GENERAL MANEUVER / GENERAL / AREAS / LANDING ZONE (LZ)

- [ ] Pick up zones         => TACTICAL GRAPHICS / COMMAND AND CONTROL AND GENERAL MANEUVER / GENERAL / AREAS / PICKUP ZONE (PZ)

- [ ] Bde Support Area (BSA)=> TACTICAL GRAPHICS / COMBAT SERVICE SUPPORT / AREA / SUPPORT AREAS / BRIGADE (BSA)

- [ ] Div Support Area (DSA)=> TACTICAL GRAPHICS / COMBAT SERVICE SUPPORT / AREA / SUPPORT AREAS / DIVISION (DSA)

**Comment by rsupnekar** [comment]
![tg1](https://cloud.githubusercontent.com/assets/25460036/25184742/509930ee-24e9-11e7-9dd8-dea02dce6434.jpg)

**Comment by rsupnekar** [comment]
Assembly Area and Objective are not showing a label.

![image](https://cloud.githubusercontent.com/assets/25460036/25185563/afd38ef4-24eb-11e7-9c41-f794ef05380f.png)
