### ISSUE TITLE
Test Line Tactical grphics

### ISSUE THREAD

**Issue by Ish-rivera** [missioncommand/emp3-android#175]
Test drawing editing and renderering of the following MilStd tactical graphics in development.

- [x] phase line            => TACTICAL GRAPHICS / COMMAND AND CONTROL AND GENERAL MANEUVER / GENERAL / LINES / PHASE LINE

- [ ] boundary (Bde - Bde, Bn -Bn, Co - Co)
                        => TACTICAL GRAPHICS / COMMAND AND CONTROL AND GENERAL MANEUVER / GENERAL / LINES / BOUNDARIES

- [x] Main Supply Route     => TACTICAL GRAPHICS / COMBAT SERVICE SUPPORT / LINES / SUPPLY ROUTES / MAIN SUPPLY ROUTE

- [x] Alternate Supply Route
                        => TACTICAL GRAPHICS / COMBAT SERVICE SUPPORT / LINES / SUPPLY ROUTES / ALTERNATE SUPPLY ROUTE

- [x] Line of contact       => TACTICAL GRAPHICS / COMMAND AND CONTROL AND GENERAL MANEUVER / GENERAL / LINES / LINE OF CONTACT

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
```TACTICAL GRAPHICS / COMMAND AND CONTROL AND GENERAL MANEUVER / GENERAL / LINES / BOUNDARIES```

The spec says:

> The line segment between each pair of anchor points will repeat all information associated with the line segment between points 1 and 2.

__The information is NOT being repeated between each segment.__

![image](https://cloud.githubusercontent.com/assets/25460191/25194430/64681e54-2508-11e7-9d83-79e6a6ee4b4f.png)

**Comment by Ish-rivera** [comment]
The spec says it is suppose to but the renderer does not. It is by design.

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
Does that mean this issue is closed?
