### ISSUE TITLE
Test Tactial Graphics

### ISSUE THREAD

**Issue by Ish-rivera** [missioncommand/emp3-android#176]
Test drawing editing and renderering of the following MilStd tactical graphics in development.

- [ ] Bridge                => WAR.GRDTRK.EQT.GRDVEH.ENGVEH.BRG

- [ ] bridge                => TACTICAL GRAPHICS / MOBILITY/SURVIVABILITY / OBSTACLE BYPASS / CROSSING SITE/WATER CROSSING / BRIDGE OR GAP

- [ ] Attack by Fire        => TACTICAL GRAPHICS / COMMAND AND CONTROL AND GENERAL MANEUVER / OFFENSE / AREAS / ATTACK BY FIRE POSITION

- [ ] Support by fire position
                        => TACTICAL GRAPHICS / COMMAND AND CONTROL AND GENERAL MANEUVER / OFFENSE / AREAS / SUPPORT BY FIRE POSITION

**Comment by rsupnekar** [comment]
Bridge or Gap: the ends are bent, but not sharp as shown in 2525C.

![image](https://cloud.githubusercontent.com/assets/25460036/25187652/ace06d6a-24f1-11e7-872a-896a37930f1b.png)

**Comment by rsupnekar** [comment]
Remove All function did not remove Bridge.

**Comment by rsupnekar** [comment]
![image](https://cloud.githubusercontent.com/assets/25460036/25187967/88ab20c4-24f2-11e7-80bd-08de82ed9421.png)
