### ISSUE TITLE
Polygon is not displayed on the map under some specific settings:

### ISSUE THREAD

**Issue by empbarney** [missioncommand/emp3-android#180]
What is the Issue?

      Polygon is not displayed on the map under some specific settings:

      CASE 1: Polygon NOT displayed on the Map when,
            Camera is zoomed out such that full globe is visible
            Polygon is setup with AltitudeMode set to RELATIVE_TO_GROUND
            Add the Polygon to the layer.

      CASE 2: Polygon is displayed on the Map When
            Camera is zoomed in, for example altitude is 10000
            Polygon is setup with AltitudeMode set to RELATIVE_TO_GROUND
            Add the Polygon to the layer.

      CASE 3: Polygon is displayed on the Map When
            Camera is zoomed out such that full globe is visible
            Polygon is setup with AltitudeMode set to ABSOLUTE
            Add the Polygon to the layer.

      
      CASE 4: Polygon NOT displayed on the Map when,
            Camera is zoomed out such that full globe is visible
            Polygon is setup with AltitudeMode set to CLAM_TO_GROUND
            Add the Polygon to the layer.

CASE 1 & 4 are the issues I am reporting.

Attachment - I have updated the 'PolygonsFragment.java' class from the tutorial. Updated code
  is at the end of the class. You play with that code to create the above four cases.

Code snippet for your reference:

        /** CODE RELATED TO THE ISSUE BEING REPORTED **/

        // Uncomment this to zoom in the camera.
//        Camera camera = new Camera();
//        camera.set(38.873, -77.058,
//            10000, WorldWind.ABSOLUTE,
//            0,
//            0,
//            0);
//
//        // Apply the new camera position
//        Globe globe = wwd.getGlobe();
//        wwd.getNavigator().setAsCamera(globe, camera);

        positions = Arrays.asList(
            Position.fromDegrees(38.873, -77.058,   100),
            Position.fromDegrees(38.873, -77.055,   100),
            Position.fromDegrees(38.871, -77.053,   100),
            Position.fromDegrees(38.869, -77.056,   100),
            Position.fromDegrees(38.870, -77.058,   100),
            Position.fromDegrees(38.873, -77.058,   100)
        );
        ShapeAttributes attrs1 = new ShapeAttributes();
        attrs1.setDrawVerticals(true); // display the extruded verticals
        attrs1.setInteriorColor(new Color(1, 1, 1, 0.5f)); // 50% transparent white
        attrs1.setOutlineWidth(3);
        poly = new Polygon(positions, attrs1);
        poly.setAltitudeMode(WorldWind.RELATIVE_TO_GROUND);
        poly.setExtrude(true); // extrude the polygon from the ground to each polygon position's altitude
        layer.addRenderable(poly);

        /** END CODE RELATED TO THE ISSUE BEING REPORTED**/

**Comment by empbarney** [comment]
NASA WorldWind team is working on this issue.

**Comment by rsupnekar** [comment]
To test build the corresponding branch, which will also build fixes for #206, #233, #234.  Run test-vandv.

Launch a map.  Create an overlay.  Zoom out so the entire globe is visible.  Set the camera altitude more (CLAMP_TO_GROUND, RELATIVE_TO_GROUND) as required in each of the instances documented above.  Then create a feature, in this case polygon.  You have to give the latitude, longitude manually, so make sure your locations are on the visible part of the map.  Touch Apply and Done and polygon should show correctly.

**Comment by rsupnekar** [comment]
Use Add, Remove, Get from the menu to create the overlay and feature.

**Comment by mubinakhan** [comment]
Reintegrate
