### ISSUE TITLE
CBRN BIOCA and CMLCA

### ISSUE THREAD

**Issue by empbarney** [missioncommand/emp3-android#189]
TACGRP.MOBSU.CBRN.BIOCA
BIOLOGICALLY CONTAMINATED AREA
G * M * NB -- -- ** ** X

TACGRP.MOBSU.CBRN.CMLCA
CHEMICALLY CONTAMINATED AREA
G * M * NC -- -- ** ** X

Polygon is drawn but in the center of the polygon there should be a symbol indicating "B" or "C" that is missing.

Why are we drawing a Polygon. Document shows a free form enclosed shape?

Same applies to DRCL also.

**Comment by empbarney** [comment]
![cmlca](https://cloud.githubusercontent.com/assets/25461029/25199456/ede4b196-2518-11e7-875c-3f698a0e6edb.png)

**Comment by empbarney** [comment]
![bioca](https://cloud.githubusercontent.com/assets/25461029/25199533/25f74abc-2519-11e7-9c3e-0ecb042197ea.png)

**Comment by Ish-rivera** [comment]
A user can use free hand drawing to generate points then draw these TG. The Yellow icon are a different MilStd icon. This is not a Bug.
