### ISSUE TITLE
Normalize Stippling Factor

### ISSUE THREAD

**Issue by Ish-rivera** [missioncommand/emp3-android#194]
We need to apply a factor to normalize the stippling factor such that the graphics render the same on devices of diff screen densities.

**Comment by Ish-rivera** [comment]
To test use branch features/#94-Normalize-Stippling-Factor


1) Using Test-Basic draw a Circle.
2) The Circle should have a dashed outline.
3) Draw A MilStd Tactical Graphic / Mobility/Surv / Obstacle Bypass / Crossing Site Water Crossing / Ford Difficulty.
4) Save The draw. The TG should be highlighted and have dash lines.
5) Deselect the graphic. The Graphic should be in black dash lines.
6) Execute this test on a tablet and the emulator. The graphics dash lines should be almost the same.

.

**Comment by rsupnekar** [comment]
Tested with Android emulator and test-basic.

Works as per the steps above.  Please reintegrate.
