### ISSUE TITLE
TACGRP.MOBSU.OBST.ATO.ATD.ATDC COMPLETE is incorrect

### ISSUE THREAD

**Issue by empbarney** [missioncommand/emp3-android#196]
TACGRP.MOBSU.OBST.ATO.ATD.ATDUC UNDER CONSTRUCTION	G * M * OA DU -- ** ** X
TACGRP.MOBSU.OBST.ATO.ATD.ATDC COMPLETE	G * M * OA DC -- ** ** X

For COMPLETE the triangles should filled.

**Comment by empbarney** [comment]
![atdc_complete_doc](https://cloud.githubusercontent.com/assets/25461029/25235191/6ef61196-25b2-11e7-8c2d-009483078019.png)

**Comment by empbarney** [comment]
![atdc-device-2017-04-20-101651](https://cloud.githubusercontent.com/assets/25461029/25235219/85212b18-25b2-11e7-9506-19905677ce0e.png)

One is supposed to be UNDER CONSTRUCTION and other is supposed to be COMPLETE. There is no difference in the display.

**Comment by michael-spinelli** [comment]
Works on the renderer test app.  I'll take a look in the eml-android tester

**Comment by michael-spinelli** [comment]
Generated kml and json have no issue either.  I think it's an issue with interpretation on the EMP-Android side.

**Comment by mubinakhan** [comment]
[Uploading Screenshot_20170711-162951[1].png...]

**Comment by mubinakhan** [comment]
Reintegrate
