### ISSUE TITLE
Deselecting Basic Shapes no longer works...

### ISSUE THREAD

**Issue by empbarney** [missioncommand/emp3-android#199]
In Capability Tester, run "Select Feature" test.
Add Overlay and Add any Basic shape "Circle, Rectangle.."
Select it using the 'Select Feature Test" button.
Now try deselecting it and feature still remains highlighted.

I have traced this down to the MapInstance. There is no issue in the Core. This is NOT related to the worldwind upgrade.

**Comment by Ish-rivera** [comment]
To test use branch #199-Deselect-basic-shapes

1) Start Capability tester.
2) Plot a Circle, a Rectangle and a square.
3) Select the Circle.
4) The Border of the circle should display in yellow.
5) Select the other 2 feature.
6) Their border should render in yellow.
7) Un-select the Rectangle and the border should return to its original color.
8) Un-select the other 2 features and their border should return to their original color.
