### ISSUE TITLE
Selecting a Point no longer works

### ISSUE THREAD

**Issue by empbarney** [missioncommand/emp3-android#200]
Run Capability Tester and start "Select Feature" test.
Add Overlay and Add "Point" feature.
Use "Select Feature Test" to elect the point feature.
Point feature is made slightly larger but is not highlighted with yellow color.

I have traced this down to the MapInstance. There is no issue in the Core. This is NOT related to the worldwind upgrade.

**Comment by Ish-rivera** [comment]
Not a bug. Point selection increases the icon scale.
