### ISSUE TITLE
Update version of com.android.tools.build:gradle

### ISSUE THREAD

**Issue by ee11cbb19052e40b07aac0ca060c23ee** [missioncommand/emp3-android#206]
Latest release it 2.3.1

**Comment by rsupnekar** [comment]
Latest is now 3.3

**Comment by rsupnekar** [comment]
Single test for #206, #233, #234.  If it builds without errors, just do a sanity test with test-basic, like drawing some features on the map.

**Comment by mubinakhan** [comment]
Reintegrate
