### ISSUE TITLE
NASA library is now versionned and on Bintray, change building procedures

### ISSUE THREAD

**Issue by rsupnekar** [missioncommand/emp3-android#233]
Previously we downloaded nightly builds of NASA worldwind-release.aar and checked it in with our source.  We also published it in our build steps.  However, now that NASA puts it on Bintray, our build.gradle files need to be updated to take it from there and also stop publishing.

**Comment by rsupnekar** [comment]
Single test for #206, #233, #234.  If it builds without errors, just do a sanity test with test-basic, like drawing some features on the map.

**Comment by mubinakhan** [comment]
Reintegrate
