### ISSUE TITLE
Map service exceptions not propagated up to user

### ISSUE THREAD

**Issue by rsupnekar** [missioncommand/emp3-android#247]
When the user attempts to add a new service, such as WMS, WMTS, WCS, or GeoPackage, the call may throw an exception.  However, such an exception is not pushed to the user.  The exception could be bad URL or layer name.

For NASA WW, WMS, WMTS and GeoPackage layers are created async and the call back errors are not part of this ticket.

**Comment by rsupnekar** [comment]
Async callback methods were added to the API because no exceptions are thrown for the call itself.

**Comment by mubinakhan** [comment]
Reintegrate.
