### ISSUE TITLE
Basic Shape editor doesn't allow changing location.

### ISSUE THREAD

**Issue by mubinakhan** [missioncommand/emp3-android#274]
Go to capability tester
-Launch Map 
-Basic Shape Editors 
-Draw shape/ Draw rectangle/ 
rectangle with 2 grey points and yellow point appears.
Yellow point spins the shape and grey points allow to change height and width but not able to change the location on the map.
![screenshot_20170911-161702 1](https://user-images.githubusercontent.com/25485443/30295102-6fec0be2-970d-11e7-83ec-7210d7c4f122.png)

**Comment by rsupnekar** [comment]
This is not a bug.  After drawing the rectangle, hit the COMPLETE button.  Then select EDIT SHAPE, put the mouse on the rectangle border and drag it to the desired location.  It works.
