### ISSUE TITLE
Update feature does not update the location values.

### ISSUE THREAD

**Issue by mubinakhan** [missioncommand/emp3-android#275]
Go to Capability tester
-Launch Map 
-from left options select add remove get / add overlay / add feature / update feature 
-dialogue appears go to update position listing to change the location of the feature .
-Feature doesn't change it's location
![screenshot_20170911-162733 1](https://user-images.githubusercontent.com/25485443/30295309-244f056c-970e-11e7-92ce-b597e3c48b49.png)

**Comment by rsupnekar** [comment]
The GUI is clumsy, but it works.  You first have to click on the map and then tap the UPDATE[TAP FOR POSITION].  Then use the Locate function to see the moved feature.
