### ISSUE TITLE
Changing position listing needs to have apply tab for the new values to store.

### ISSUE THREAD

**Issue by mubinakhan** [missioncommand/emp3-android#276]
![screenshot_20170911-163004 1](https://user-images.githubusercontent.com/25485443/30295524-e8794da8-970e-11e7-9a7c-f21bbb45e983.png)
Go to capability tester
-Launch Map / Add remove get / add overlay/add feature / add geo- circle.
-dialogue appears / add values ( radius )
-change the defaulted position list 
-Values don't change until add another row for new listing. 
See attached image.
![screenshot_20170911-163011 1](https://user-images.githubusercontent.com/25485443/30295517-e3b5321e-970e-11e7-9db5-517bc52219a8.png)

**Comment by rsupnekar** [comment]
Added in branch #277
