### ISSUE TITLE
Draw shapes do not plot when layers are on the Test basic app.

### ISSUE THREAD

**Issue by mubinakhan** [missioncommand/emp3-android#280]
-Launch Test basic app 
-Menu / Layers / add WCS / add LOA 
-Menu / Draw menu / draw circle or line / 
-Shapes spread on the map and do not plot on on spot

**Comment by mubinakhan** [comment]
![image1](https://user-images.githubusercontent.com/25485443/30496438-5ee3d6e6-9a1d-11e7-8126-8ab3e45c8824.PNG)

**Comment by mubinakhan** [comment]
https://jira.di2e.net/secure/enav/#?query=project%20%3D%20%22EMP%22%20AND%20fixVersion%20%3D%20%22Unscheduled%22%20AND%20cycleName%20in%20(%22ER%202%20Sprint%2019%22)

**Comment by mubinakhan** [comment]
https://jira.di2e.net/secure/enav/#?query=project%20%3D%20%22EMP%22%20AND%20fixVersion%20%3D%20%22Unscheduled%22%20AND%20cycleName%20in%20(%22EMP3-API%22)

**Comment by mubinakhan** [comment]
https://jira.di2e.net/secure/enav/#?query=project%20%3D%20%22EMP%22%20AND%20fixVersion%20%3D%20%22Unscheduled%22%20AND%20cycleName%20in%20(%22Release%202.3.0%22)

**Comment by mubinakhan** [comment]
https://jira.di2e.net/secure/enav/#?query=project%20%3D%20%22EMP%22%20AND%20fixVersion%20%3D%20%22Unscheduled%22%20AND%20cycleName%20in%20(%22Release%202.4.0%22)

**Comment by JACochran** [comment]
I am unable to replicate the issue.  I have followed the steps and attempted to re-create the bug. Closing due to unable to replicate.
