### ISSUE TITLE
Draw mode of Bridge Or Gap symbol not 2525C compliant

### ISSUE THREAD

**Issue by michaeltk3** [missioncommand/emp3-android#282]
The "BRIDGE OR GAP" symbol from the 2525C spec requires: "The two sides must be parallel"

When drawing one of these symbols in EMP (in draw mode), there are 4 points that are editable by the user. The user can move these points around so that the two side of the symbol are no longer parallel. The draw mode for this symbol should restrict the user's edits to keep the sides being parallel.
![capture](https://user-images.githubusercontent.com/32075980/30559994-7f398be8-9c84-11e7-8e85-01c5a4bf9720.JPG)

**Comment by alberto-acevedo** [comment]
code removed

**Comment by rsupnekar** [comment]
Fixed in version 2.9.2-SNAPSHOT
