### ISSUE TITLE
Draw mode of BYPASS EASY symbol not 2525C compliant

### ISSUE THREAD

**Issue by michaeltk3** [missioncommand/emp3-android#293]
The "BYPASS EASY" symbol from the 2525C spec specifies that "Points 1 and 2 determine the graphic’s height and point 3 determines its length." When drawing this feature on the map, the user is able to create a parallelogram shape (see attached image). The drawing mode should restrict the user to a rectangular shape only.

![bypass_easy](https://user-images.githubusercontent.com/32075980/31031455-9ad360b8-a526-11e7-8d3e-ae93a258ebf7.JPG)

**Comment by rsupnekar** [comment]
Fix added in branch #293-bypass-easy.  To test, build the branch and run test-basic.  

From the menu (3 dots in the top right corner), choose:
Test->Draw Menu->Draw MilStd->Draw Tactical Graphic
Enter a name in the dialog.  For the Symbol choose:
Tactical Graphics->Mobility/Survivability->Obstacle Bypass->Obstacle Bypass Difficulty->Bypass Easy
When the symbol appears pull one of the extreme control points (not center).
Graphic should stay rectangular
