### ISSUE TITLE
Investigate reorganization of repository

### ISSUE THREAD

**Issue by stevendlander** [missioncommand/emp3-android#325]
As a maintainer or contributor, I would like to organize the repository with a few submodules as possible to reduce confusion, assist with debugging, and enable test reports to work out-of-the-box.

This task should investigate the level of effort for reorganizing the repository.

**Comment by jrummel** [comment]
Updated readmes based on our conversations as to why there are so many modules in this project. Can continue to look into this if need be.

**Comment by jrummel** [comment]
Going to reorganize tests as they all exist in sdk-view with the hope that reorganization fixes the Travis build stalls as well. Will also investigate level of effort for total reorganization. Will comment again with my thoughts and close this ticket out.

**Comment by rsupnekar** [comment]
Closed as priorities have changed
