### ISSUE TITLE
DMS (lat/long) grid longitudes missing for multiples of 45 degrees

### ISSUE THREAD

**Issue by rsupnekar** [missioncommand/emp3-android#359]
Longitudes at 45, 90, ... are missing.

**Comment by rsupnekar** [comment]
![screenshot from 2017-11-08 10-19-45](https://user-images.githubusercontent.com/25460036/32556824-729ae1d6-c46e-11e7-8c93-a532e036c66f.png)

**Comment by rsupnekar** [comment]
Here's what I got back from NASA:



This is a limitation in WW Android. CLAMP_TO_GROUND path features are drawn into offscreen tiles, which are in turn drawn on the global terrain surface. EMP grid lines disappear when the grid’s path features align with these tile boundaries. The paths are rasterized, but their output fragments are clipped by the tile’s boundary. Additionally, CLAMP_TO_GROUND feature tiles start as 90x90 degree regions and subdivide as the zooms level increases, hence the sporadic disappearance at 45 degrees as well as 90 degrees. If EMP had grid lines at intervals of 22.5 and 11.25 (and so on), you’d likely see those disappear under certain zoom distances as well.

**Comment by pdavidc** [comment]
@rsupnekar We've implemented a change in NASAWorldWind/WorldWindAndroid#185 designed to address this issue. Please take a look and let us know whether this EMP issue is resolved.

**Comment by rsupnekar** [comment]
Closed.  The new NASA WW fixes this issue.
![screenshot from 2017-12-13 15-28-17](https://user-images.githubusercontent.com/25460036/33961534-6de7a5ba-e01c-11e7-9a30-ffd3c5b9cdb7.png)
