### ISSUE TITLE
Remove all dependencies on DI2E

### ISSUE THREAD

**Issue by ee11cbb19052e40b07aac0ca060c23ee** [missioncommand/emp3-android#36]
The goal is to remove all DI2E references from codebase.

This includes:
* credentials
* repository URLs
* artifact files

---

This will need to be a 2-phase effort.

~~__Phase1__ involves getting our artifacts publishing to and resolving from Bintray. This phase will still have some dependencies on artifacts being published to DI2E, notably: cmapi and mil-sym-android.~~

__Phase2__ involves updating cmapi and ~~mil-sym-android~~ to build from Travis and deploy to Bintray. Once completed we will be able to remove all DI2E reference due to no longer requiring artifacts hosted there.

---
### Status
- [x] emp3-android publishes to Bintray
- [x] mil-sym-android builds on Travis and publishing to Bintray
- [ ] cmapi  builds on Travis and publishing to Bintray
- [ ] remove all code/script/dependency references to DI2E

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
This will need to be a 2-phase effort.

__Phase1__ involves getting our artifacts publishing to and resolving from Bintray. This phase will still have some dependencies on artifacts being published to DI2E, notably: cmapi and mil-sym-android.

__Phase2__ involves updating cmapi and mil-sym-android to build from Travis and deploy to Bintray. Once completed we will be able to remove all DI2E reference due to no longer requiring artifacts hosted there.

**Comment by rsupnekar** [comment]
Completed by merging branch release/v2.7.1
