### ISSUE TITLE
Stroke style changes when crossing some longitudes

### ISSUE THREAD

**Issue by rsupnekar** [missioncommand/emp3-android#360]
Seems to happen at multiples of 90 degrees.
![screenshot from 2017-11-08 10-08-01](https://user-images.githubusercontent.com/25460036/32556320-16066522-c46d-11e7-9731-fe66abd11874.png)

**Comment by pdavidc** [comment]
@rsupnekar Have you had a chance to validate the fix from NASAWorldWind/WorldWindAndroid#173 ?

**Comment by rsupnekar** [comment]
Yes.
![screenshot from 2017-11-29 12-49-27](https://user-images.githubusercontent.com/25460036/33430361-44f7ce60-d59e-11e7-8c48-c1eaa1b1b6cf.png)
