### ISSUE TITLE
Large Rendered Circles have Jagged Lines

### ISSUE THREAD

**Issue by wluebke-rii** [missioncommand/emp3-android#394]
## Expected Behavior
When large (in terms of pixels) circles are rendered on the map, expect to see a relatively smooth circle rendered.

## Actual Behavior
Large rendered circles have jagged edges due to being rendered as a polygon with few enough sides to notice.

**Comment by jrummel** [comment]
@zglueck @pdavidc 
Working branch is issue#394-ellipse-and-circle-rendering
Added maximum interval of 256, using test-basic app zooming in all of the way causes the attached image to occur. Radius appears to be 1.0
![250_interval](https://user-images.githubusercontent.com/14984046/34845193-064cd2b8-f6e2-11e7-8fbc-9bcb9f0dde51.png)

**Comment by jrummel** [comment]
Worldwind team has identified the issue in their shape renderer. Closing this ticket out, will be fixed next worldwind version.
