### ISSUE TITLE
Map Zoomed In Pan

### ISSUE THREAD

**Issue by keyserSoze42** [missioncommand/emp3-android#395]
## Expected Behavior
Map should stay a location when all the way zoomed in

## Actual Behavior
The user completely zooms in on any map location and attempts to pan the map by moving your finger on the touchscreen. The map will jump to random coordinates on the globe (also completely zoomed in).

## Steps to Reproduce the Problem

  1. zoom in all the way on the map
  2.  try to move and observe your location
 

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by JACochran** [comment]
I attempted to replicate this issue by using emp-android-examples kmz-importexport as well as minimap example with EMP versions 3.1.2 and 3.0.1.  Neither replicated the behavior described.  I tested on an android emulator as well as an android tablet (Shield Tablet k1).  

I also tried it on the MFoCS using the pluggable map application and was able to reproduce the behavior.  I noticed that if you double click to zoom in (and do not use the provided zoom in and zoom out buttons) it does NOT jump to the other part of the globe. If you do use the zoom in and zoom out buttons, the jumping DOES occur.  This behavior is not limited to touch behavior but is also replicated by
using a mouse as well.  

I also attempted using the latest apk of WorldWind (3.1.2) and downloaded it to the MFoCS and the behavior still occurred.  

Based on my investigation I would suggest looking at how the zoom in and zoom out buttons are behaving on the pluggable map application.  Please let me know if you think that I am missing something or if you want further investigation on EMP that I have not tried.
