### ISSUE TITLE
Mac OS Dev Environment

### ISSUE THREAD

**Issue by jrummel** [missioncommand/emp3-android#422]
Mac OS Dev environment setup needs to be figured out and documented.

Currently Android Studio for Mac OS cannot read environment variables from System.getenv. This call is present in several of our build scripts.

**Comment by jrummel** [comment]
Alternative would be to update the build script to pull android.jar remotely. `compileOnly files("${System.getenv("ANDROID_HOME")}/platforms/android-${android_compileSdkVersion}/android.jar")` must be replaced in this case.

**Comment by jrummel** [comment]
Possibly need to switch both google-maps-android-cmgn and sdk-api to be aars so we don't have to include that dependency.

**Comment by jpettitt1** [comment]
Figured out a fix for this: 

### Background First
Android Studio creates a `local.properties` file that defines `sdk.dir={your sdk's path here}`. Just opening the project once in Android Studio will create this file, or if building command line you could create the file manually.

### Fix
In all build.gradle files where the below line is present
```
compileOnly files("${System.getenv("ANDROID_HOME")}/platforms/android-${android_compileSdkVersion}/android.jar")
```
Replace it with the the following code
```
Properties localProps = new Properties()
localProps.load(project.rootProject.file('local.properties').newDataInputStream())
compileOnly files("${localProps.getProperty('sdk.dir')}/platforms/android-${android_compileSdkVersion}/android.jar")
```

### Summary
This works great with changing any additional environment variables, and I believe should less OS version dependent than the other potential fixes I've found.

**Comment by jrummel** [comment]
Confirmed that this is working. As we suspected you will need to open the project in Android Studio to get the local.properties file to get generated or manually create it. If manually creating it (i.e. using eclipse for whatever reason) you would need to create a local.properties file at the root project folder and place `sdk.dir=/path/to/android/sdk` inside of it.

**Comment by jrummel** [comment]
Current issue with this fix lies with travis ci as it doesn't have a local.properties file available to it. Adding local.properties to git causes changes to be detected on end developer environment anytime they load the repo into android studio, even when included in .gitignore. Still investigating.

**Comment by jrummel** [comment]
Consensus on this issue is to change sdk-api and google-maps-android-cmgn to be compiled as aar's instead of jars and removing the offending line entirely. We will also remove the line from geolib as it shouldn't be necessary there anyway. We will need to double check that the transition from jars to aars won't cause issues at Jan 3rds meeting.

**Comment by rsupnekar** [comment]
Closed because building this code on Mac OSX is not a requirement.
