### ISSUE TITLE
Setting symbol code causing exception when used with the default MilStdSymbol constructor

### ISSUE THREAD

**Issue by michaeltk3** [missioncommand/emp3-android#444]
## Expected Behavior
I can create a MilStdSymbol and then set its symbol code...
MilStdSymbol newFeature = new MilStdSymbol();
newFeature.setSymbolCode(...);

## Actual Behavior

setSymbolCode() call is throwing IllegalStateException:
`01-03 10:32:08.682  1575  1575 E AndroidRuntime: java.lang.IllegalStateException: Invalid operation. Symbol code is not set
01-03 10:32:08.682  1575  1575 E AndroidRuntime:     at mil.emp3.api.MilStdSymbol.validate(MilStdSymbol.java:1038)
01-03 10:32:08.682  1575  1575 E AndroidRuntime:     at mil.emp3.api.MilStdSymbol.isSinglePoint(MilStdSymbol.java:858)
01-03 10:32:08.682  1575  1575 E AndroidRuntime:     at mil.emp3.api.MilStdSymbol.setSymbolCode(MilStdSymbol.java:660)`

## Steps to Reproduce the Problem

  1. See expected behavior

## Specifications

  - Version: EMP 3.1.6
  - Platform: Android
  - Subsystem:

**Comment by JACochran** [comment]
I need a little more information in order to replicate the issue.  Can you tell me what value you are setting the Symbol Code to? If you can give me the exact String that causes the problem I can track this down.

Thank you!

**Comment by michaeltk3** [comment]
Jenifer,

If you are using EMP 1.3.6, it's as simple as...

MilStdSymbol newFeature = new MilStdSymbol(); // note we are not setting
the symbol code in the constructor call
newFeature.setSymbolCode("GFGPAAR---****X");

The symbol code value actually doesn't make a difference. What happens is
that in the setSymbolCode method (
https://github.com/missioncommand/emp3-android/blob/89514526bb7b139c52dce459298287072b4bafe5/sdk/sdk-api/src/main/java/mil/emp3/api/MilStdSymbol.java),
the isSinglePoint() method is getting called prior to:

this.getRenderable().setSymbolCode(symbolCode);

...and since isSinglePoint() calls validate() which checks for a symbol
code, it ends up throwing an exeption. I was able to replicate this in your
"basic" version of your test tool by clicking CONTINUE in the dialog below.
It will crash the app.

[image: Inline image 1]

Michael Kirk
Research Innovations Inc. (RII)

**Comment by JACochran** [comment]
Hey Micheal,

I realized that two seconds after I posted that.  I am able to recreate the bug and I already have a fix.  I am just adding tests so that this won't occur again in the future.  It should be ready for our next release.  Thank you for finding it!

Jenifer

**Comment by michaeltk3** [comment]
No problem. Do you happen to know when the next release will be?

Michael Kirk
Research Innovations Inc. (RII)

**Comment by JACochran** [comment]
We plan on having our next release on Tuesday January 9th.
