### ISSUE TITLE
GeoJSON needs to parse Bounding Box

### ISSUE THREAD

**Issue by rsupnekar** [missioncommand/emp3-android#5]
GeoJSON needs to parse Bounding Box, the current parser ignores it.  There is no bounding box for EMP IFeature.

**Comment by mubinakhan** [comment]
![screenshot_20170209-121318 1](https://cloud.githubusercontent.com/assets/25485443/22794417/1f2ec554-eec1-11e6-9a5d-599f3ec8ae44.png)
![screenshot_20170209-121335 1](https://cloud.githubusercontent.com/assets/25485443/22794423/2609a1b4-eec1-11e6-98d8-c349d357e18a.png)

**Comment by rsupnekar** [comment]
Works for the properties we support
