### ISSUE TITLE
For a Polygon, if fill pattern is other than solid then fill color doesn't take effect

### ISSUE THREAD

**Issue by empbarney** [missioncommand/emp3-android#6]
A Polygon can have one of the three fill patterns, solid, hatched, and cross-hatched. If fill pattern is hatched or cross-hatched then grid lines should be drawn with the color specified in the fill style.

**Comment by empbarney** [comment]
Test instructions:

build feature/Issue-6-Polygon-Fill
Install and run Capability Tester
Launch map
Start "Add remove Get" Test.
Add a polygon.
Change the Fill Style to hatched/cross-hatched
Change the fill color and ensure that grid lines show up with the color you selected.

**Comment by mubinakhan** [comment]
Reintegrate
![screenshot_20170206-163843 1](https://cloud.githubusercontent.com/assets/25485443/22667408/a0be062c-ec8a-11e6-9cb8-a04116e528b4.png)

**Comment by empbarney** [comment]
Verified.
