### ISSUE TITLE
Circle and Ellipse spread around the map when zooming out.

### ISSUE THREAD

**Issue by mubinakhan** [missioncommand/emp3-android#66]
Feature ellipse and circle move around the map and relocate when zoomed out.
Launch Map on capability testers.
*Add overlay.
* Add feature ( Circle or ellipse)
* Locate the feature by selecting "locate" from menu.
* Circle will show .Now zoom out.
*Map will have circle in improper shape.
*Ellipse behaves same way

**Comment by empbarney** [comment]
Fixed with render-er release 0.1.22
