### ISSUE TITLE
Limitation needed when adding values (height ,width, radius etc) for features 

### ISSUE THREAD

**Issue by mubinakhan** [missioncommand/emp3-android#76]
when adding values for features there should be a maximum size limit set for all the features which require manually input data so the features appear on the map properly.
For example adding circle  to the map  without restrictions on radius results in improper behavior.

**Comment by empbarney** [comment]
Added checks to make sure that properties like height, width, radii are positive and non NaN.
Added check to make sure they meet the minimum size requirement.
Will NOT make any change to limit the sizes.
