### ISSUE TITLE
Add KML Export capability to EMP

### ISSUE THREAD

**Issue by Ish-rivera** [missioncommand/emp3-android#77]
Add an API which generates  a KML document from the EMP overlay or feature. The KML document shall contain all child objects.

**Comment by Ish-rivera** [comment]
To test us branch 77-add-kml-export-capability.

1) Build and run testBasic.
2) Plot several features at least on of each type. I.E. Circle ellipse, rectangle square, point, line, polygon, single point and multi point milstd.
3) Select from the menu Export To KML / Export Map. This sgould export all feature on the map to a kml file located in the pictures directory on the devices file system.
4) Transfer the file to your PC.
5) Import the via to GoogleEarth.
6) The feature should look the same.

**Comment by rsupnekar** [comment]
![image](https://cloud.githubusercontent.com/assets/25460036/24370565/d77c3dbe-12f5-11e7-9beb-be9c4d4e2c48.png)

**Comment by rsupnekar** [comment]
Reintegrate
