### ISSUE TITLE
Update feature function doesn't update the location of any feature.

### ISSUE THREAD

**Issue by mubinakhan** [missioncommand/emp3-android#81]
* Add overlay 
* Add any feature
* Locate the feature on the map.
* Update feature by selecting the feature.
* Change the Longitude or latitude and select update.
* feature's Position doesn't change on the map after updating.

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
_NOTE: The instructions above pertain to the test-vandv application._

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
Side note: How do I progress past this screen?

![111](https://cloud.githubusercontent.com/assets/25460191/24553137/21ab8d32-15f7-11e7-8cbe-f15657d9c4f8.png)

**Comment by empbarney** [comment]
Looks like you are using an emulator and Apply and Done buttons are hidden.

**Comment by empbarney** [comment]
![nexus_7_api_23](https://cloud.githubusercontent.com/assets/25461029/24554752/ada6a0d8-15fc-11e7-9948-7c5a895da360.png)

**Comment by mubinakhan** [comment]
Reintegrate
