### ISSUE TITLE
mgrs grid lines

### ISSUE THREAD

**Issue by Ish-rivera** [missioncommand/emp3-android#87]
To Test use development.
Use test basic. 
1) Via the menu / settings / Map Grid. Select MGRS.
2) The MGRS grid should show up on the map.
3) Pan / Zoom the map.
4) The grid should correctly redraw.
5) Alter the camera heading, title and roll
6) The map grid should redraw correctly.
7) There is an anomaly in the Norway area. This is a known issue.
8) Test all over the world.
9) Set the grid setting to UTM and repeat.
10 Execute and test on the MFOCS

**Comment by mubinakhan** [comment]
Wasn't able to perform on MFOCS and UTM grid is giving the same error as MGRS ( ref in email )

**Comment by Ish-rivera** [comment]
I created a branch #78-MGRS-grid-lines. I can no reproduce the exception. But I added an additional check. Please retest and if it fails add detail in your comment.
