### ISSUE TITLE
Add ability to recognize and ignore events based on user-provided source information

### ISSUE THREAD

**Issue by ee11cbb19052e40b07aac0ca060c23ee** [missioncommand/emp3-android#91]
# Motivation

Currently emp3-android has no straightforward mechanism to identify the source that triggered an event. This is desirable in cases where a developer wishes to ignore events originating from code which they authored.

For example, Listing 1.1 demonstrates how a developer could register for Overlay events, and the developer's code shown in Listing 1.2 triggers an Overlay event. There is not enough information provided to event listeners that would allow it to recognize, and optionally ignore, an event that was sourced from their own code.

__Listing 1.1 Instantiate an Overlay and register a listener__
```java
Overlay o = new Overlay();
o.addContainerEventListener(new IContainerEventListener() {
  public void onEvent(ContainerEvent event) {
    // handle event
  }
});
```
__Listing 1.2 Adding a feature to the Overlay__
```java
o.addFeature(new MilStdSymbol());
```

# Proposed Solutions

## ~~Solution 1~~

Add methods to IContainer (and any other interfaces that can have an Event associated with it, like ICamera) and IEventListener that support supplying user-defined data as shown in Listing 1.3 and Listing 1.4

__Listing 1.3 Added methods to IContainer to support providing user-defined data__
```java
public interface IContainer extends IGeoContainer {
    void setUserData(Object userData);

    Object getUserData();
    <T> T getUserData(Class<T> type);
...
```
__Listing 1.4 Added methods to IEventListener to support providing user-defined data__
```java
public interface IEventListener<T extends IEvent> {
    void setUserData(Object userData);

    Object getUserData();
    <T> T getUserData(Class<T> type);
...
```
### Backward Compatibility
Developers who have implemented listeners will need to now also implement the above three methods, regardless of their usage.

## Solution 2
Augment the Event object to include 'userData' or 'source' information

## ~~Solution 3~~
Overload the IEventListener.onEvent() method to provide 'userData' or 'source' information

## Solution 4
Overload `addXXX(...)` methods to accept 'userData' or 'source' information

## ~~Solution 5~~
Allow an 'eventFilter' to be provided when registering an event listener

**Comment by rsupnekar** [comment]
I prefer the event filter idea.  I know this shifts the burden to the api user.

**Comment by empbarney** [comment]
Please add a use case to show how this will be used and a sequence diagram.

**Comment by empbarney** [comment]
How does any of these solutions work in case of Camera Event?

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
Solutions 2 and 4 were implemented. see #108
