### ISSUE TITLE
Basic shape editors -Drawing Square crashing capability Tester

### ISSUE THREAD

**Issue by mubinakhan** [missioncommand/emp3-android#92]
[file.txt](https://github.com/missioncommand/emp3-android/files/862937/file.txt)

**Comment by mubinakhan** [comment]
*Install Capability tester and launch map
*Run "Basic Shape editors "
*Select "Add IDraw EventListener"
* Select "Set a stroke style" Set stippling factor to 6 and width to 10.
*Draw shapes/ Draw square 
* Square should appear on the map. Move the square with control points.
* Spin the globe/map few times around
* Map stops and dialogue with app not responding appears .( see image)
* Log file is attached for reference

**Comment by mubinakhan** [comment]
![screenshot_20170322-171354 1](https://cloud.githubusercontent.com/assets/25485443/24221180/a6fd180a-0f23-11e7-96a0-63d5608c8c30.png)

**Comment by mubinakhan** [comment]
[file.txt](https://github.com/missioncommand/emp3-android/files/865192/file.txt)

**Comment by mubinakhan** [comment]
please see the attached new log captured 
[file1.txt](https://github.com/missioncommand/emp3-android/files/865463/file1.txt)

**Comment by mdeutch3** [comment]
I was able to find a significant delay in the function that extracts the numeric fields from the modifiers. @michael-spinelli I commented the call to SymbolUtiliites.isNumber which seems to take much longer when the numeric string is in exponential form. I've checked in the change to the Renderer source.

**Comment by mdeutch3** [comment]
SymbolUtilities.isNumber was revised to remove the bottleneck and is much faster for numeric strings, including those using exponential notation. I reversed the previous change and it is using isNumber. The Renderer source change has been checked in.

**Comment by mubinakhan** [comment]
Reintegrate
