### ISSUE TITLE
Text From MP TG do not display

### ISSUE THREAD

**Issue by Ish-rivera** [missioncommand/emp3-android#96]
Text components generated from the multi point tactical graphic renderer are not being displayed.

**Comment by empbarney** [comment]
if (cameraAltitude <= this.getMapInstance().getFarDistanceThreshold()) {
                for(Renderable renderable: renderableLabelList) {
                    renderable.render(renderContext);
                }
            }

Above code hides it. Once you zoom in, you will see it.

Additionally the Text is drawn beyond the bounds, e.g. string FLOT is beyond the bound.
