### ISSUE TITLE
Text associated with MGRS is not parallel to the latitude lines.

### ISSUE THREAD

**Issue by empbarney** [missioncommand/emp3-android#97]
I have attached a screen capture along with camera settings.
![device-2017-03-24-142254](https://cloud.githubusercontent.com/assets/25461029/24310652/29c52aa0-10a7-11e7-8e94-b9f71cb0fb73.png)

**Comment by Ish-rivera** [comment]
To test use branch #97-Text-mgrs-is-not-parallel

1) Run test basic and select setting / map grid lines / MGRS from the menu.
2) The map grid lines will appear.
3) Change the heading, roll and tilt of the camera.
4) The Text of the gird lines should remain aligned to parallel lines.

**Comment by rsupnekar** [comment]
reintegrate
